services:

  db:
    image: postgres
    environment:
      POSTGRES_DB: tools-shop
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
